#!/usr/bin/env bash
set -e

# deploy_working
#
# Uploads the working directory to the webserver (prompting for the password
# for user "warriorsband").

rsync -ah --chmod=g+rwx --progress --del --exclude-from "deploy_excludes.txt" \
    `dirname $0`/www/ \
    warriorsband@warriorsband.com:~/warriorsband.com/
