#!/usr/bin/env bash
set -e

# deploy_working
#
# Uploads the working directory to the webserver (prompting for the password
# for user "warriorsband").

rsync -ah --progress --del --exclude-from "deploy_excludes.txt" \
    ~/Documents/Programming/warriorsband/ \
    warriorsband@warriorsband.com:~/warriorsband.com/
